In [4]:
import sys,os
sys.path.append('..')
sys.path.append(os.path.expanduser('~/github/lltk'))
import lltk
from largeliterarymodels import *
from largeliterarymodels.tasks.classify_genre import *
from tqdm import tqdm
from largeliterarymodels.llm import GEMINI_PRO, GEMINI_FLASH, CLAUDE_OPUS
import random
MODEL = CLAUDE_OPUS

In [5]:
C=lltk.load('arc_fiction')
# C.meta

In [6]:
df = C.meta.copy()
df['genre_raw'] = df['genre_raw'].fillna('')
# df=df.query('1475<=year<1700')
df = df.query('1700<=year<1800')
df = df[(df.genre_raw=='') | (df.genre_raw=='Fiction')]
len(df)

3111

In [7]:
n_max=1000
texts = [C.text(id) for id in tqdm(df.index)]
texts = random.sample(texts, min(len(texts), n_max))
len(texts)

100%|██████████| 3111/3111 [00:01<00:00, 3054.30it/s]

1000

In [8]:
texts[0].meta

{'_id': '_arc_fiction/mdp/39015055067113',
 '_corpus': 'arc_fiction',
 'id': 'mdp/39015055067113',
 'author': 'Burnet, Thomas,',
 'author_norm': 'burnet',
 'corpus': 'hathi_englit',
 'genre': 'Fiction',
 'genre_raw': 'Fiction',
 'path_freqs': 'hathi/freqs/mdp/39015055067113.json',
 'title': 'A second tale of a tub;',
 'title_norm': 'a second tale of a tub',
 'year': np.int32(1715)}

In [9]:
prompt=format_lltk_text_for_classification(texts[0])
print(prompt)

Title: A second tale of a tub;
Author: Burnet
Year: 1700-1800

In [10]:
task = GenreTask()

In [11]:
task.run(prompt, model=MODEL)

GenreClassification(genre='Essay', genre_raw='', author_first_name='Thomas', is_translated=False, translated_from='', year_estimated=1715, confidence=0.72, reasoning="This appears to be a satirical political pamphlet by Thomas Burnet (the younger), playing on Swift's 'A Tale of a Tub.' Works with this title from this period are typically political satire or polemical essays rather than sustained prose fiction.", notes="Thomas Burnet (c.1694–1753), son of the bishop and historian Gilbert Burnet, wrote several satirical pamphlets. 'A Second Tale of a Tub' (c.1715) is a political satire that alludes to Swift's famous 'A Tale of a Tub' (1704). Despite the word 'tale' in the title, it is a satirical essay or pamphlet rather than a work of prose fiction. It engages with contemporary political and ecclesiastical controversies.")

In [12]:
prompts = [format_lltk_text_for_classification(t) for t in texts]

results = task.map(prompts, model=MODEL)

Extracting GenreClassification (claude-opus-4-6): 100%|██████████| 969/969 [24:29<00:00,  1.52s/it]

In [29]:
assert len(results) == len(texts) == len(prompts)

In [30]:
r=results[-1]

In [31]:
r.model_dump()

{'genre': 'Fiction',
 'genre_raw': 'Imaginary voyage',
 'author_first_name': 'Savinien',
 'is_translated': True,
 'translated_from': 'French',
 'year_estimated': 1657,
 'confidence': 0.97,
 'reasoning': "Cyrano de Bergerac's 'Voyage to the Moon' (L'Autre Monde: ou les États et Empires de la Lune) is a classic French imaginary voyage, a pioneering work of proto-science fiction, translated into English.",
 'notes': "Originally published posthumously in French as 'Histoire comique des États et Empires de la Lune' (1657), this work by Savinien de Cyrano de Bergerac is one of the earliest examples of science fiction. The narrator travels to the moon and encounters its inhabitants, providing a vehicle for philosophical satire on religion, science, and society. It was followed by a companion volume about the sun. Multiple English translations appeared in the 18th century."}

In [32]:
results[-1], texts[-1]

(GenreClassification(genre='Fiction', genre_raw='Imaginary voyage', author_first_name='Savinien', is_translated=True, translated_from='French', year_estimated=1657, confidence=0.97, reasoning="Cyrano de Bergerac's 'Voyage to the Moon' (L'Autre Monde: ou les États et Empires de la Lune) is a classic French imaginary voyage, a pioneering work of proto-science fiction, translated into English.", notes="Originally published posthumously in French as 'Histoire comique des États et Empires de la Lune' (1657), this work by Savinien de Cyrano de Bergerac is one of the earliest examples of science fiction. The narrator travels to the moon and encounters its inhabitants, providing a vehicle for philosophical satire on religion, science, and society. It was followed by a companion volume about the sun. Multiple English translations appeared in the 18th century."),
 Bergerac, A Voyage To The Moon (1754) [_arc_fiction/LitAndLang1/0001000100])

In [33]:
import pandas as pd
ld = [{**t.meta, **{'llm_'+k:v for k,v in r.model_dump().items()}} for t,r in zip(texts,results)]
odf = pd.DataFrame(ld).fillna('')
# odf

In [34]:
odf.llm_genre_raw.value_counts().head(10)

llm_genre_raw
                      237
Novel                 142
Novel, sentimental     93
Chapbook               74
Tale                   42
Tale, oriental         40
Novel, epistolary      33
Fiction, satire        30
Novel, amatory         22
Novel, picaresque      19
Name: count, dtype: int64

In [35]:
odf.columns

Index(['_id', '_corpus', 'id', 'author', 'author_norm', 'corpus', 'genre',
       'genre_raw', 'path_freqs', 'title', 'title_norm', 'year', 'llm_genre',
       'llm_genre_raw', 'llm_author_first_name', 'llm_is_translated',
       'llm_translated_from', 'llm_year_estimated', 'llm_confidence',
       'llm_reasoning', 'llm_notes', 'is_translated', 'genre_source',
       'genre_source_reason', 'notes'],
      dtype='object')

In [36]:
correct_odf = odf[
    (odf.year == odf.llm_year_estimated)
    & odf.apply(lambda r: bool((r.author in {'Unknown','Anon','Anonymous',''}) or r.llm_author_first_name) and r.llm_author_first_name in r.author, axis=1)
    # & (odf.llm_confidence>=0.9)
].fillna('')
correct_odf['llm_genre_source_reason'] = correct_odf['llm_reasoning']
correct_odf['llm_llm_confidence'] = correct_odf['llm_confidence']
correct_odf[['id','corpus','author','title','year'] + [c for c in correct_odf if c.startswith('llm_')]]

,id,corpus,author,title,year,llm_genre,llm_genre_raw,llm_author_first_name,llm_is_translated,llm_translated_from,llm_year_estimated,llm_confidence,llm_reasoning,llm_notes,llm_genre_source_reason,llm_llm_confidence
0,mdp/39015055067113,hathi_englit,"Burnet, Thomas,",A second tale of a tub;,1715.0,Essay,,Thomas,False,,1715,0.72,This appears to be a satirical political pamph...,"Thomas Burnet (c.1694–1753), son of the bishop...",This appears to be a satirical political pamph...,0.72
12,HistAndGeo/0739200300,ecco,,"The whole life, and conversation, birth and pa...",1707.0,Fiction,Criminal biography,,False,,1707,0.72,This is a criminal biography/pamphlet recounti...,This is a typical early 18th-century criminal ...,This is a criminal biography/pamphlet recounti...,0.72
18,LitAndLang1/0250600500,ecco,,The Lancashire collier girl. A true story,1795.0,Fiction,"Novel, sentimental",,False,,1795,0.72,"Despite the subtitle 'A true story,' works wit...",The Lancashire Collier Girl: A True Story is a...,"Despite the subtitle 'A true story,' works wit...",0.72
19,LL1560,litlab,"Williams, Helen Maria",Edwin and Eltruda. A legendary tale. By a youn...,1782.0,Poetry,,Helen Maria,False,,1782,0.90,Helen Maria Williams's 'Edwin and Eltruda' (17...,Edwin and Eltruda: A Legendary Tale (1782) was...,Helen Maria Williams's 'Edwin and Eltruda' (17...,0.90
20,LL1221,litlab,Unknown,"The Birmingham counterfeit; or, invisible spec...",1772.0,Fiction,"Novel, sentimental",,False,,1772,0.85,The title explicitly identifies itself as 'a s...,"The Birmingham Counterfeit; or, Invisible Spec...",The title explicitly identifies itself as 'a s...,0.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
978,K061006.000,tedjdh,"Defoe, Daniel, 1661?-1731",THE SHORTEST-WAY WITH THE DISSENTERS: OR PROPO...,1702.0,Essay,,Daniel,False,,1702,0.97,This is Daniel Defoe's famous satirical pamphl...,The Shortest-Way with the Dissenters (1702) by...,This is Daniel Defoe's famous satirical pamphl...,0.97
983,1764/Fiction/1468,bpo,,"A CHAPTER read, as if from the Bible, by a Gen...",1764.0,Essay,,,False,,1764,0.75,This is a satirical pamphlet written in biblic...,This pamphlet is almost certainly related to t...,This is a satirical pamphlet written in biblic...,0.75
988,HistAndGeo/0091100400,ecco,,"The true and remarkable trial, condemnation, a...",1793.0,History,,,False,,1793,0.90,This is a factual account of the trial and exe...,Louis XVI was executed by guillotine on Januar...,This is a factual account of the trial and exe...,0.90
993,LL1358,litlab,Unknown,The life and villainous actions of that notori...,1725.0,Fiction,Criminal biography,,False,,1725,0.88,"This is a criminal biography of Jonathan Wild,...",Jonathan Wild (c.1683–1725) was a famous Londo...,"This is a criminal biography of Jonathan Wild,...",0.88
996,LitAndLang1/0027900302,ecco,"Robinson, Mary","Vancenza; or, the dangers of credulity",1792.0,Fiction,"Novel, Gothic",Mary,False,,1792,0.95,"Vancenza; or, the Dangers of Credulity is a Go...","Vancenza; or, the Dangers of Credulity (1792) ...","Vancenza; or, the Dangers of Credulity is a Go...",0.95

In [37]:
len(correct_odf)

209

In [38]:
# correct_odf

In [39]:
# task.stash.df

In [40]:
def get_record(row):
    o = {}
    o['_id'] = f'_{row.corpus}/{row.id}'
    o['genre_source'] = f'llm:{MODEL}'
    for k in ['genre','genre_raw','is_translated','translated_from','genre_source_reason','notes', 'llm_confidence']:
        val = row['llm_'+k]
        if val!='':
            o[k] = val
    return o

In [41]:
records = [get_record(row) for i,row in correct_odf.iterrows()]
records

[{'_id': '_hathi_englit/mdp/39015055067113',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Essay',
  'is_translated': False,
  'genre_source_reason': "This appears to be a satirical political pamphlet by Thomas Burnet (the younger), playing on Swift's 'A Tale of a Tub.' Works with this title from this period are typically political satire or polemical essays rather than sustained prose fiction.",
  'notes': "Thomas Burnet (c.1694–1753), son of the bishop and historian Gilbert Burnet, wrote several satirical pamphlets. 'A Second Tale of a Tub' (c.1715) is a political satire that alludes to Swift's famous 'A Tale of a Tub' (1704). Despite the word 'tale' in the title, it is a satirical essay or pamphlet rather than a work of prose fiction. It engages with contemporary political and ecclesiastical controversies.",
  'llm_confidence': 0.72},
 {'_id': '_ecco/HistAndGeo/0739200300',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'genre_raw': 'Criminal biography',
  'is_translated': False,
  'genre_source_reason': 'This is a criminal biography/pamphlet recounting the life and trial of Richard Mosely, executed for murder. Criminal biographies of this period are conventionally classified as fiction in ESTC, as they typically blend factual reportage with sensationalized narrative embellishment.',
  'notes': 'This is a typical early 18th-century criminal biography pamphlet, detailing the life, trial, and execution of Richard Mosely for the murder of his grandmother Mary Payton in Sedgley, Staffordshire, in 1707. Such pamphlets were popular ephemeral literature, sold at executions and by chapbook sellers. While based on real events, they are conventionally grouped with fiction due to their heavy narrative embellishment and formulaic structure. The genre sits at the boundary between journalism, biography, and popular fiction.',
  'llm_confidence': 0.72},
 {'_id': '_ecco/LitAndLang1/0250600500',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'genre_raw': 'Novel, sentimental',
  'is_translated': False,
  'genre_source_reason': "Despite the subtitle 'A true story,' works with titles like 'The Lancashire Collier Girl' in this period are typically sentimental fiction or novellas presenting themselves as true accounts. The pattern of '[Place] [humble occupation] girl' is characteristic of late 18th-century sentimental fiction.",
  'notes': "The Lancashire Collier Girl: A True Story is a late 18th-century work that appears to be a short novel or tale in the sentimental tradition, likely published in the 1790s. The 'true story' subtitle was a common convention in fiction of this period to lend verisimilitude. The subject of a humble working-class girl suggests a sentimental or moral narrative about virtue in low life. The author is not identified on the title page.",
  'llm_confidence': 0.72},
 {'_id': '_litlab/LL1560',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Poetry',
  'is_translated': False,
  'genre_source_reason': "Helen Maria Williams's 'Edwin and Eltruda' (1782) is a verse tale — a narrative poem in the legendary/sentimental mode, not prose fiction.",
  'notes': "Edwin and Eltruda: A Legendary Tale (1782) was Helen Maria Williams's first published work, issued anonymously as 'by a young lady.' It is a narrative poem in heroic couplets telling a tragic love story set in medieval England. Williams went on to become well known for her poetry and her letters from revolutionary France.",
  'llm_confidence': 0.9},
 {'_id': '_litlab/LL1221',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'genre_raw': 'Novel, sentimental',
  'is_translated': False,
  'genre_source_reason': "The title explicitly identifies itself as 'a sentimental romance' and the structure ('in two volumes') is typical of late 18th-century prose fiction. This is a novel from the sentimental tradition.",
  'notes': 'The Birmingham Counterfeit; or, Invisible Spectator (c.1772) is an anonymous sentimental romance published in two volumes. The title suggests themes of deception and observation common in 18th-century fiction. It is a relatively obscure work of the period, not widely discussed in literary histories.',
  'llm_confidence': 0.85},
 {'_id': '_ecco/LitAndLang1/0757400503',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'genre_raw': 'Novel, epistolary',
  'is_translated': False,
  'genre_source_reason': 'Desmond (1792) by Charlotte Smith is a well-known epistolary novel set against the backdrop of the French Revolution, combining a love story with political commentary.',
  'notes': 'Desmond (1792) by Charlotte Smith is an epistolary novel in which the titular character, Desmond, is in love with a married woman, Geraldine Verney, whose husband is dissolute and cruel. The novel is notable for its sympathetic treatment of the French Revolution and its progressive political views, which were controversial at the time. Smith was one of the most prominent novelists and poets of the late 18th century.',
  'llm_confidence': 0.95},
 {'_id': '_tedjdh/K079595.001',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'genre_raw': 'Picaresque',
  'is_translated': False,
  'genre_source_reason': "The title explicitly states it is 'in imitation of Gil Blas,' the classic picaresque novel by Lesage, and follows the adventures of a character 'supposed to be written by himself,' a standard picaresque framing device.",
  'notes': "Modern Times; or, The Adventures of Gabriel Outcast (1785) by John Trusler is a picaresque novel modeled on Lesage's Gil Blas. Trusler (1735–1820) was an English clergyman, author, and eccentric publisher known for a wide range of works including conduct books, abridgments, and this satirical novel depicting contemporary English society through the adventures of its roguish protagonist.",
  'llm_confidence': 0.95},
 {'_id': '_tedjdh/K039355.000',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Poetry',
  'is_translated': False,
  'genre_source_reason': "Hannah Cowley's 'The Maid of Arragon' (1780) is a verse tale — a narrative poem rather than prose fiction. Despite the subtitle 'A Tale,' it is written in verse.",
  'notes': "The Maid of Arragon: A Tale (1780) by Hannah Cowley (née Parkhouse, 1743–1809) is a narrative poem. Cowley was primarily known as a dramatist (The Belle's Stratagem, 1780) but also wrote poetry. This work is in verse form and should be classified as poetry rather than fiction.",
  'llm_confidence': 0.82},
 {'_id': '_litlab/LL1372',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'genre_raw': 'Tale',
  'is_translated': False,
  'genre_source_reason': "The title 'The Matrons: Six Short Histories' suggests a collection of short prose fiction narratives. This appears to be a mid-18th-century collection of tales, possibly inspired by or related to the 'Matron of Ephesus' tradition from Petronius, presenting stories of women's conduct.",
  'notes': "The Matrons (1762) is a collection of six short tales, likely prose fiction narratives centered on female characters. The work may draw on the classical tradition of the Matron of Ephesus story from Petronius's Satyricon, a popular theme in 18th-century literature. The anonymous authorship and the use of 'histories' in the subtitle is typical of 18th-century fiction collections. The term 'histories' in this period frequently denotes fictional narratives rather than factual accounts.",
  'llm_confidence': 0.72},
 {'_id': '_ecco/LitAndLang1/0013500201',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'genre_raw': 'Novel, sentimental',
  'is_translated': False,
  'genre_source_reason': "Joseph de Maimieux was a French author known for sentimental novels; 'Le comte de Saint-Méran' appears to be a French-language novel published in the late 18th century. Its appearance in an English catalog may indicate it was printed in London for a French-reading audience or is a cataloging artifact.",
  'notes': "Joseph de Maimieux (1753–1820) was a French writer and inventor of the 'pasigraphie' universal writing system. He also wrote novels and other literary works. 'Le comte de Saint-Méran' is a French-language novel, likely sentimental in character, consistent with the literary fashions of the 1780s. This text appears in English catalogs but is in French, not a translation into English.",
  'llm_confidence': 0.7},
 {'_id': '_litlab/LL0718',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Biography',
  'is_translated': False,
  'genre_source_reason': 'Arthur Maynwaring (1668–1712) was a real person — a Whig political writer and Kit-Cat Club member. This is a posthumous collection of his works with a biographical account, not fiction.',
  'notes': "Arthur Maynwaring (1668–1712) was an English political writer, journalist, and Whig propagandist closely associated with the Duchess of Marlborough and the Kit-Cat Club. This posthumous volume, likely edited by John Oldmixon and published around 1715, combines a biographical life with a collection of Maynwaring's previously unpublished writings, including political tracts, translations, and verse. It is a biography and collected works, not fiction.",
  'llm_confidence': 0.92},
 {'_id': '_litlab/LL1495',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'genre_raw': 'Novel, sentimental',
  'is_translated': False,
  'genre_source_reason': "'The history of Lady Frances Tylney' follows the typical naming convention of 18th-century sentimental novels, with fictional-sounding character names and the keyword 'True delicacy' suggesting a sentimental theme.",
  'notes': "This appears to be an anonymous sentimental novel from the latter half of the 18th century. The title structure — an abstract moral quality followed by 'the history of' fictional characters — is characteristic of the period's sentimental fiction. The names Lady Frances Tylney and Henry Cecil suggest aristocratic protagonists typical of the genre. Published circa 1769.",
  'llm_confidence': 0.85},
 {'_id': '_hathi_englit/mdp/39015030208071',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'genre_raw': 'Novel, epistolary',
  'is_translated': False,
  'genre_source_reason': "This title follows the convention of epistolary fiction popular in the late 18th century, presenting fictional letters from a noble figure as a framing device. The anonymous authorship and the generic 'peeress of England' suggest a fictional construct rather than genuine correspondence.",
  'notes': 'Letters from a Peeress of England to her Eldest Son (c. 1784) is an epistolary work that presents itself as advice from a noblewoman to her son. While it could be a genuine conduct book in letter form, the anonymous publication and the convention of the period strongly suggest it is either epistolary fiction or a didactic work using a fictional epistolary frame. It may border on conduct literature rather than pure fiction.',
  'llm_confidence': 0.72},
 {'_id': '_ecco/HistAndGeo/0127400400',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'genre_raw': 'Novel, It Narrative',
  'is_translated': False,
  'genre_source_reason': "This is an 'it-narrative' or 'novel of circulation' told from the perspective of a cat, a popular subgenre in the mid-to-late 18th century.",
  'notes': 'The Life and Adventures of a Cat (1760) is an anonymous it-narrative, a genre in which animals or objects narrate their own life stories as they pass through various owners and situations. These works typically served as vehicles for social satire, offering commentary on human behavior through the eyes of a non-human narrator. This particular work follows a cat named Tom through various adventures and was popular enough to be reprinted multiple times.',
  'llm_confidence': 0.9},
 {'_id': '_hathi_englit/mdp/39015078561373',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'genre_raw': 'Fiction, satire',
  'is_translated': False,
  'genre_source_reason': "This is Charles Gildon's satirical attack on Daniel Defoe, published in 1719 shortly after Robinson Crusoe. It parodies Defoe's life and work using the format of Crusoe's title.",
  'notes': "The Life and Strange Surprizing Adventures of Mr. D---- De F-- (1719) by Charles Gildon is a satirical pamphlet attacking Daniel Defoe, parodying the title and style of Robinson Crusoe. Gildon mocks Defoe's career, politics, and literary pretensions. It includes a dialogue in which Crusoe and Friday confront their creator. While it has a satirical narrative frame, it is primarily a personal attack and literary satire rather than a sustained novel.",
  'llm_confidence': 0.95},
 {'_id': '_litlab/LL0085',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Letters',
  'is_translated': True,
  'translated_from': 'French',
  'genre_source_reason': "Bellegarde's letters are didactic/conduct letters addressed to a lady of the court on 'curious and useful subjects,' making them closer to epistolary essays or conduct literature than fiction. The title explicitly states they are translated from French.",
  'notes': 'Jean-Baptiste Morvan de Bellegarde (1648–1734) was a French abbé and prolific author of conduct books, moral reflections, and letters on polite behavior and learning. His works were widely translated into English in the early 18th century. These letters, addressed to a lady of the French court, are didactic in nature, offering advice and reflections on various subjects rather than constituting a fictional narrative. The English translation includes a preface by the translator.',
  'llm_confidence': 0.75},
 {'_id': '_tedjdh/K000637.000',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'genre_raw': 'Fiction, satire',
  'is_translated': False,
  'genre_source_reason': "This is the third part of Arbuthnot's 'Law is a Bottomless Pit' (1712), the John Bull political satire series, which uses sustained fictional allegory with characters representing nations (John Bull = England, Nicholas Frog = the Dutch, etc.) to satirize the War of the Spanish Succession.",
  'notes': "John Bull Still in His Senses (1712) by John Arbuthnot is the third pamphlet in a series of five that collectively form 'The History of John Bull.' These satirical allegories, written to support the Tory push for peace during the War of the Spanish Succession, created the enduring character of John Bull as a personification of England. The series uses a fictional lawsuit narrative to allegorize European politics. Arbuthnot was a physician, mathematician, and member of the Scriblerus Club alongside Swift and Pope.",
  'llm_confidence': 0.92},
 {'_id': '_tedjdh/K102171.000',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Criticism',
  'is_translated': False,
  'genre_source_reason': "This appears to be a critical commentary on Sterne's Tristram Shandy, published under the pseudonym 'Jeremiah Kunastrokius M.D.' It is not the novel itself but rather explanatory remarks upon it. The attribution to Sterne in the catalog may reflect the subject matter rather than actual authorship; such parasitic commentaries were common.",
  'notes': "This is one of several contemporary responses to Laurence Sterne's The Life and Opinions of Tristram Shandy, Gentleman (1759–1767). 'Jeremiah Kunastrokius' is a comic pseudonym (the name appears as a character reference in Tristram Shandy itself). The work purports to explain the morals and politics of Sterne's novel. It is likely not by Sterne himself but is cataloged under his name because it concerns his work. It belongs to the genre of critical commentary or satirical explication rather than fiction proper.",
  'llm_confidence': 0.72},
 {'_id': '_ecco/LitAndLang1/0375900101',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'genre_raw': 'Tale, oriental',
  'is_translated': True,
  'translated_from': 'French',
  'genre_source_reason': 'This is a continuation of the Arabian Nights, translated from the French edition by Dom Chavis and Jacques Cazotte, consisting of oriental tales in the frame narrative tradition.',
  'notes': "Arabian Tales (1792) is an English translation of the 'Suite des Mille et une Nuits' compiled by Dom Denis Chavis, a Syrian priest, and Jacques Cazotte, the French author. Published in French as part of the Cabinet des fées (vols. 38-41, 1788-1790), it purported to be translated from an Arabic manuscript but was largely fabricated or heavily embellished by Cazotte. The English translation appeared in the 1790s and was marketed as a continuation of Galland's famous Arabian Nights Entertainments.",
  'llm_confidence': 0.95},
 {'_id': '_tedjdh/K109095.002',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Criticism',
  'is_translated': True,
  'genre_source_reason': "Charlotte Lennox's Shakespear Illustrated is a work of literary criticism that collects and translates the source narratives for Shakespeare's plays, accompanied by critical remarks comparing the sources to the plays. Despite containing translated fiction, the work itself is a critical study.",
  'notes': "Shakespear Illustrated (1753-54, 3 vols.) by Charlotte Lennox (author of The Female Quixote, 1752) was one of the first systematic studies of Shakespeare's sources. It translates the Italian novellas, chronicles, and romances that Shakespeare drew upon, with Lennox's critical commentary often arguing that Shakespeare degraded his sources, particularly in his treatment of female characters. Samuel Johnson contributed a dedication. The work contains translations from Italian and other languages but is fundamentally a work of literary criticism.",
  'llm_confidence': 0.95},
 {'_id': '_hathi_englit/nyp/33433074918768',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'genre_raw': 'Novel, anti-Jacobin',
  'is_translated': False,
  'genre_source_reason': "George Walker's The Vagabond (1799) is a well-known anti-Jacobin novel satirizing the radical philosophies of Godwin, Holcroft, and others.",
  'notes': 'The Vagabond (1799) by George Walker is an anti-Jacobin novel that follows a character influenced by radical philosophy (particularly that of William Godwin) through a series of misadventures designed to demonstrate the absurdity and danger of revolutionary ideas. It is one of the most prominent examples of the conservative novelistic response to the French Revolution and radical thought in 1790s England.',
  'llm_confidence': 0.9},
 {'_id': '_ecco_tcp/K030489.000',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'genre_raw': 'Chapbook',
  'is_translated': False,
  'genre_source_reason': "This is one of Hannah More's Cheap Repository Tracts, short moral tales written for popular distribution among the poor. Despite their brevity and didactic purpose, they are prose fiction.",
  'notes': "The Bad Bargain: or, The World Set Up to Sale is one of Hannah More's Cheap Repository Tracts (1795–1798), a series of moral and religious tales designed to counter radical and irreligious popular literature. These tracts were distributed widely and cheaply, functioning as improving chapbooks. More wrote many of them herself, using simple narratives and allegories to convey Christian moral lessons.",
  'llm_confidence': 0.85},
 {'_id': '_tedjdh/K102448.001',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Essay',
  'is_translated': False,
  'genre_source_reason': "The Babbler is a collection of periodical essays by Hugh Kelly, originally published in Owen's Weekly Chronicle. It is a compilation of moral and entertaining essays in the tradition of The Spectator, not fiction.",

In [43]:
pd.DataFrame(records).fillna('')

,_id,genre_source,genre,is_translated,genre_source_reason,notes,llm_confidence,genre_raw,translated_from
0,_hathi_englit/mdp/39015055067113,llm:claude-opus-4-6,Essay,False,This appears to be a satirical political pamph...,"Thomas Burnet (c.1694–1753), son of the bishop...",0.72,,
1,_ecco/HistAndGeo/0739200300,llm:claude-opus-4-6,Fiction,False,This is a criminal biography/pamphlet recounti...,This is a typical early 18th-century criminal ...,0.72,Criminal biography,
2,_ecco/LitAndLang1/0250600500,llm:claude-opus-4-6,Fiction,False,"Despite the subtitle 'A true story,' works wit...",The Lancashire Collier Girl: A True Story is a...,0.72,"Novel, sentimental",
3,_litlab/LL1560,llm:claude-opus-4-6,Poetry,False,Helen Maria Williams's 'Edwin and Eltruda' (17...,Edwin and Eltruda: A Legendary Tale (1782) was...,0.90,,
4,_litlab/LL1221,llm:claude-opus-4-6,Fiction,False,The title explicitly identifies itself as 'a s...,"The Birmingham Counterfeit; or, Invisible Spec...",0.85,"Novel, sentimental",
...,...,...,...,...,...,...,...,...,...
204,_tedjdh/K061006.000,llm:claude-opus-4-6,Essay,False,This is Daniel Defoe's famous satirical pamphl...,The Shortest-Way with the Dissenters (1702) by...,0.97,,
205,_bpo/1764/Fiction/1468,llm:claude-opus-4-6,Essay,False,This is a satirical pamphlet written in biblic...,This pamphlet is almost certainly related to t...,0.75,,
206,_ecco/HistAndGeo/0091100400,llm:claude-opus-4-6,History,False,This is a factual account of the trial and exe...,Louis XVI was executed by guillotine on Januar...,0.90,,
207,_litlab/LL1358,llm:claude-opus-4-6,Fiction,False,"This is a criminal biography of Jonathan Wild,...",Jonathan Wild (c.1683–1725) was a famous Londo...,0.88,Criminal biography,
208,_ecco/LitAndLang1/0027900302,llm:claude-opus-4-6,Fiction,False,"Vancenza; or, the Dangers of Credulity is a Go...","Vancenza; or, the Dangers of Credulity (1792) ...",0.95,"Novel, Gothic",

In [44]:
C.propagate_from(records, dry_run=True)

Would write 209 annotation entries:
  litlab: 75
  ecco: 57
  hathi_englit: 37
  tedjdh: 20
  ecco_tcp: 5
  earlyprint: 4
  bpo: 4
  clmet: 3
  chadwyck: 3
  gale_amfic: 1

[{'_id': '_hathi_englit/mdp/39015055067113',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Essay',
  'is_translated': False,
  'genre_source_reason': "This appears to be a satirical political pamphlet by Thomas Burnet (the younger), playing on Swift's 'A Tale of a Tub.' Works with this title from this period are typically political satire or polemical essays rather than sustained prose fiction.",
  'notes': "Thomas Burnet (c.1694–1753), son of the bishop and historian Gilbert Burnet, wrote several satirical pamphlets. 'A Second Tale of a Tub' (c.1715) is a political satire that alludes to Swift's famous 'A Tale of a Tub' (1704). Despite the word 'tale' in the title, it is a satirical essay or pamphlet rather than a work of prose fiction. It engages with contemporary political and ecclesiastical controversies.",
  'llm_confidence': 0.72},
 {'_id': '_ecco/HistAndGeo/0739200300',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': 'This is a criminal biography/pamphlet recounting the life and trial of Richard Mosely, executed for murder. Criminal biographies of this period are conventionally classified as fiction in ESTC, as they typically blend factual reportage with sensationalized narrative embellishment.',
  'notes': 'This is a typical early 18th-century criminal biography pamphlet, detailing the life, trial, and execution of Richard Mosely for the murder of his grandmother Mary Payton in Sedgley, Staffordshire, in 1707. Such pamphlets were popular ephemeral literature, sold at executions and by chapbook sellers. While based on real events, they are conventionally grouped with fiction due to their heavy narrative embellishment and formulaic structure. The genre sits at the boundary between journalism, biography, and popular fiction.',
  'llm_confidence': 0.72,
  'genre_raw': 'Criminal biography'},
 {'_id': '_ecco/LitAndLang1/0250600500',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "Despite the subtitle 'A true story,' works with titles like 'The Lancashire Collier Girl' in this period are typically sentimental fiction or novellas presenting themselves as true accounts. The pattern of '[Place] [humble occupation] girl' is characteristic of late 18th-century sentimental fiction.",
  'notes': "The Lancashire Collier Girl: A True Story is a late 18th-century work that appears to be a short novel or tale in the sentimental tradition, likely published in the 1790s. The 'true story' subtitle was a common convention in fiction of this period to lend verisimilitude. The subject of a humble working-class girl suggests a sentimental or moral narrative about virtue in low life. The author is not identified on the title page.",
  'llm_confidence': 0.72,
  'genre_raw': 'Novel, sentimental'},
 {'_id': '_litlab/LL1560',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Poetry',
  'is_translated': False,
  'genre_source_reason': "Helen Maria Williams's 'Edwin and Eltruda' (1782) is a verse tale — a narrative poem in the legendary/sentimental mode, not prose fiction.",
  'notes': "Edwin and Eltruda: A Legendary Tale (1782) was Helen Maria Williams's first published work, issued anonymously as 'by a young lady.' It is a narrative poem in heroic couplets telling a tragic love story set in medieval England. Williams went on to become well known for her poetry and her letters from revolutionary France.",
  'llm_confidence': 0.9},
 {'_id': '_litlab/LL1221',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "The title explicitly identifies itself as 'a sentimental romance' and the structure ('in two volumes') is typical of late 18th-century prose fiction. This is a novel from the sentimental tradition.",
  'notes': 'The Birmingham Counterfeit; or, Invisible Spectator (c.1772) is an anonymous sentimental romance published in two volumes. The title suggests themes of deception and observation common in 18th-century fiction. It is a relatively obscure work of the period, not widely discussed in literary histories.',
  'llm_confidence': 0.85,
  'genre_raw': 'Novel, sentimental'},
 {'_id': '_ecco/LitAndLang1/0757400503',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': 'Desmond (1792) by Charlotte Smith is a well-known epistolary novel set against the backdrop of the French Revolution, combining a love story with political commentary.',
  'notes': 'Desmond (1792) by Charlotte Smith is an epistolary novel in which the titular character, Desmond, is in love with a married woman, Geraldine Verney, whose husband is dissolute and cruel. The novel is notable for its sympathetic treatment of the French Revolution and its progressive political views, which were controversial at the time. Smith was one of the most prominent novelists and poets of the late 18th century.',
  'llm_confidence': 0.95,
  'genre_raw': 'Novel, epistolary'},
 {'_id': '_tedjdh/K079595.001',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "The title explicitly states it is 'in imitation of Gil Blas,' the classic picaresque novel by Lesage, and follows the adventures of a character 'supposed to be written by himself,' a standard picaresque framing device.",
  'notes': "Modern Times; or, The Adventures of Gabriel Outcast (1785) by John Trusler is a picaresque novel modeled on Lesage's Gil Blas. Trusler (1735–1820) was an English clergyman, author, and eccentric publisher known for a wide range of works including conduct books, abridgments, and this satirical novel depicting contemporary English society through the adventures of its roguish protagonist.",
  'llm_confidence': 0.95,
  'genre_raw': 'Picaresque'},
 {'_id': '_tedjdh/K039355.000',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Poetry',
  'is_translated': False,
  'genre_source_reason': "Hannah Cowley's 'The Maid of Arragon' (1780) is a verse tale — a narrative poem rather than prose fiction. Despite the subtitle 'A Tale,' it is written in verse.",
  'notes': "The Maid of Arragon: A Tale (1780) by Hannah Cowley (née Parkhouse, 1743–1809) is a narrative poem. Cowley was primarily known as a dramatist (The Belle's Stratagem, 1780) but also wrote poetry. This work is in verse form and should be classified as poetry rather than fiction.",
  'llm_confidence': 0.82},
 {'_id': '_litlab/LL1372',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "The title 'The Matrons: Six Short Histories' suggests a collection of short prose fiction narratives. This appears to be a mid-18th-century collection of tales, possibly inspired by or related to the 'Matron of Ephesus' tradition from Petronius, presenting stories of women's conduct.",
  'notes': "The Matrons (1762) is a collection of six short tales, likely prose fiction narratives centered on female characters. The work may draw on the classical tradition of the Matron of Ephesus story from Petronius's Satyricon, a popular theme in 18th-century literature. The anonymous authorship and the use of 'histories' in the subtitle is typical of 18th-century fiction collections. The term 'histories' in this period frequently denotes fictional narratives rather than factual accounts.",
  'llm_confidence': 0.72,
  'genre_raw': 'Tale'},
 {'_id': '_ecco/LitAndLang1/0013500201',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "Joseph de Maimieux was a French author known for sentimental novels; 'Le comte de Saint-Méran' appears to be a French-language novel published in the late 18th century. Its appearance in an English catalog may indicate it was printed in London for a French-reading audience or is a cataloging artifact.",
  'notes': "Joseph de Maimieux (1753–1820) was a French writer and inventor of the 'pasigraphie' universal writing system. He also wrote novels and other literary works. 'Le comte de Saint-Méran' is a French-language novel, likely sentimental in character, consistent with the literary fashions of the 1780s. This text appears in English catalogs but is in French, not a translation into English.",
  'llm_confidence': 0.7,
  'genre_raw': 'Novel, sentimental'},
 {'_id': '_litlab/LL0718',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Biography',
  'is_translated': False,
  'genre_source_reason': 'Arthur Maynwaring (1668–1712) was a real person — a Whig political writer and Kit-Cat Club member. This is a posthumous collection of his works with a biographical account, not fiction.',
  'notes': "Arthur Maynwaring (1668–1712) was an English political writer, journalist, and Whig propagandist closely associated with the Duchess of Marlborough and the Kit-Cat Club. This posthumous volume, likely edited by John Oldmixon and published around 1715, combines a biographical life with a collection of Maynwaring's previously unpublished writings, including political tracts, translations, and verse. It is a biography and collected works, not fiction.",
  'llm_confidence': 0.92},
 {'_id': '_litlab/LL1495',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "'The history of Lady Frances Tylney' follows the typical naming convention of 18th-century sentimental novels, with fictional-sounding character names and the keyword 'True delicacy' suggesting a sentimental theme.",
  'notes': "This appears to be an anonymous sentimental novel from the latter half of the 18th century. The title structure — an abstract moral quality followed by 'the history of' fictional characters — is characteristic of the period's sentimental fiction. The names Lady Frances Tylney and Henry Cecil suggest aristocratic protagonists typical of the genre. Published circa 1769.",
  'llm_confidence': 0.85,
  'genre_raw': 'Novel, sentimental'},
 {'_id': '_hathi_englit/mdp/39015030208071',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "This title follows the convention of epistolary fiction popular in the late 18th century, presenting fictional letters from a noble figure as a framing device. The anonymous authorship and the generic 'peeress of England' suggest a fictional construct rather than genuine correspondence.",
  'notes': 'Letters from a Peeress of England to her Eldest Son (c. 1784) is an epistolary work that presents itself as advice from a noblewoman to her son. While it could be a genuine conduct book in letter form, the anonymous publication and the convention of the period strongly suggest it is either epistolary fiction or a didactic work using a fictional epistolary frame. It may border on conduct literature rather than pure fiction.',
  'llm_confidence': 0.72,
  'genre_raw': 'Novel, epistolary'},
 {'_id': '_ecco/HistAndGeo/0127400400',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "This is an 'it-narrative' or 'novel of circulation' told from the perspective of a cat, a popular subgenre in the mid-to-late 18th century.",
  'notes': 'The Life and Adventures of a Cat (1760) is an anonymous it-narrative, a genre in which animals or objects narrate their own life stories as they pass through various owners and situations. These works typically served as vehicles for social satire, offering commentary on human behavior through the eyes of a non-human narrator. This particular work follows a cat named Tom through various adventures and was popular enough to be reprinted multiple times.',
  'llm_confidence': 0.9,
  'genre_raw': 'Novel, It Narrative'},
 {'_id': '_hathi_englit/mdp/39015078561373',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "This is Charles Gildon's satirical attack on Daniel Defoe, published in 1719 shortly after Robinson Crusoe. It parodies Defoe's life and work using the format of Crusoe's title.",
  'notes': "The Life and Strange Surprizing Adventures of Mr. D---- De F-- (1719) by Charles Gildon is a satirical pamphlet attacking Daniel Defoe, parodying the title and style of Robinson Crusoe. Gildon mocks Defoe's career, politics, and literary pretensions. It includes a dialogue in which Crusoe and Friday confront their creator. While it has a satirical narrative frame, it is primarily a personal attack and literary satire rather than a sustained novel.",
  'llm_confidence': 0.95,
  'genre_raw': 'Fiction, satire'},
 {'_id': '_litlab/LL0085',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Letters',
  'is_translated': True,
  'genre_source_reason': "Bellegarde's letters are didactic/conduct letters addressed to a lady of the court on 'curious and useful subjects,' making them closer to epistolary essays or conduct literature than fiction. The title explicitly states they are translated from French.",
  'notes': 'Jean-Baptiste Morvan de Bellegarde (1648–1734) was a French abbé and prolific author of conduct books, moral reflections, and letters on polite behavior and learning. His works were widely translated into English in the early 18th century. These letters, addressed to a lady of the French court, are didactic in nature, offering advice and reflections on various subjects rather than constituting a fictional narrative. The English translation includes a preface by the translator.',
  'llm_confidence': 0.75,
  'translated_from': 'French'},
 {'_id': '_tedjdh/K000637.000',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "This is the third part of Arbuthnot's 'Law is a Bottomless Pit' (1712), the John Bull political satire series, which uses sustained fictional allegory with characters representing nations (John Bull = England, Nicholas Frog = the Dutch, etc.) to satirize the War of the Spanish Succession.",
  'notes': "John Bull Still in His Senses (1712) by John Arbuthnot is the third pamphlet in a series of five that collectively form 'The History of John Bull.' These satirical allegories, written to support the Tory push for peace during the War of the Spanish Succession, created the enduring character of John Bull as a personification of England. The series uses a fictional lawsuit narrative to allegorize European politics. Arbuthnot was a physician, mathematician, and member of the Scriblerus Club alongside Swift and Pope.",
  'llm_confidence': 0.92,
  'genre_raw': 'Fiction, satire'},
 {'_id': '_tedjdh/K102171.000',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Criticism',
  'is_translated': False,
  'genre_source_reason': "This appears to be a critical commentary on Sterne's Tristram Shandy, published under the pseudonym 'Jeremiah Kunastrokius M.D.' It is not the novel itself but rather explanatory remarks upon it. The attribution to Sterne in the catalog may reflect the subject matter rather than actual authorship; such parasitic commentaries were common.",
  'notes': "This is one of several contemporary responses to Laurence Sterne's The Life and Opinions of Tristram Shandy, Gentleman (1759–1767). 'Jeremiah Kunastrokius' is a comic pseudonym (the name appears as a character reference in Tristram Shandy itself). The work purports to explain the morals and politics of Sterne's novel. It is likely not by Sterne himself but is cataloged under his name because it concerns his work. It belongs to the genre of critical commentary or satirical explication rather than fiction proper.",
  'llm_confidence': 0.72},
 {'_id': '_ecco/LitAndLang1/0375900101',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': True,
  'genre_source_reason': 'This is a continuation of the Arabian Nights, translated from the French edition by Dom Chavis and Jacques Cazotte, consisting of oriental tales in the frame narrative tradition.',
  'notes': "Arabian Tales (1792) is an English translation of the 'Suite des Mille et une Nuits' compiled by Dom Denis Chavis, a Syrian priest, and Jacques Cazotte, the French author. Published in French as part of the Cabinet des fées (vols. 38-41, 1788-1790), it purported to be translated from an Arabic manuscript but was largely fabricated or heavily embellished by Cazotte. The English translation appeared in the 1790s and was marketed as a continuation of Galland's famous Arabian Nights Entertainments.",
  'llm_confidence': 0.95,
  'genre_raw': 'Tale, oriental',
  'translated_from': 'French'},
 {'_id': '_tedjdh/K109095.002',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Criticism',
  'is_translated': True,
  'genre_source_reason': "Charlotte Lennox's Shakespear Illustrated is a work of literary criticism that collects and translates the source narratives for Shakespeare's plays, accompanied by critical remarks comparing the sources to the plays. Despite containing translated fiction, the work itself is a critical study.",
  'notes': "Shakespear Illustrated (1753-54, 3 vols.) by Charlotte Lennox (author of The Female Quixote, 1752) was one of the first systematic studies of Shakespeare's sources. It translates the Italian novellas, chronicles, and romances that Shakespeare drew upon, with Lennox's critical commentary often arguing that Shakespeare degraded his sources, particularly in his treatment of female characters. Samuel Johnson contributed a dedication. The work contains translations from Italian and other languages but is fundamentally a work of literary criticism.",
  'llm_confidence': 0.95},
 {'_id': '_hathi_englit/nyp/33433074918768',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "George Walker's The Vagabond (1799) is a well-known anti-Jacobin novel satirizing the radical philosophies of Godwin, Holcroft, and others.",
  'notes': 'The Vagabond (1799) by George Walker is an anti-Jacobin novel that follows a character influenced by radical philosophy (particularly that of William Godwin) through a series of misadventures designed to demonstrate the absurdity and danger of revolutionary ideas. It is one of the most prominent examples of the conservative novelistic response to the French Revolution and radical thought in 1790s England.',
  'llm_confidence': 0.9,
  'genre_raw': 'Novel, anti-Jacobin'},
 {'_id': '_ecco_tcp/K030489.000',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "This is one of Hannah More's Cheap Repository Tracts, short moral tales written for popular distribution among the poor. Despite their brevity and didactic purpose, they are prose fiction.",
  'notes': "The Bad Bargain: or, The World Set Up to Sale is one of Hannah More's Cheap Repository Tracts (1795–1798), a series of moral and religious tales designed to counter radical and irreligious popular literature. These tracts were distributed widely and cheaply, functioning as improving chapbooks. More wrote many of them herself, using simple narratives and allegories to convey Christian moral lessons.",
  'llm_confidence': 0.85,
  'genre_raw': 'Chapbook'},
 {'_id': '_tedjdh/K102448.001',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Essay',
  'is_translated': False,
  'genre_source_reason': "The Babbler is a collection of periodical essays by Hugh Kelly, originally published in Owen's Weekly Chronicle. It is a compilation of moral and entertaining essays in the tradition of The Spectator, not fiction.",

In [45]:
C.propagate_from(records)

Wrote 209 annotation entries from external
  litlab: 75
  ecco: 57
  hathi_englit: 37
  tedjdh: 20
  ecco_tcp: 5
  earlyprint: 4
  bpo: 4
  clmet: 3
  chadwyck: 3
  gale_amfic: 1

[{'_id': '_hathi_englit/mdp/39015055067113',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Essay',
  'is_translated': False,
  'genre_source_reason': "This appears to be a satirical political pamphlet by Thomas Burnet (the younger), playing on Swift's 'A Tale of a Tub.' Works with this title from this period are typically political satire or polemical essays rather than sustained prose fiction.",
  'notes': "Thomas Burnet (c.1694–1753), son of the bishop and historian Gilbert Burnet, wrote several satirical pamphlets. 'A Second Tale of a Tub' (c.1715) is a political satire that alludes to Swift's famous 'A Tale of a Tub' (1704). Despite the word 'tale' in the title, it is a satirical essay or pamphlet rather than a work of prose fiction. It engages with contemporary political and ecclesiastical controversies.",
  'llm_confidence': 0.72},
 {'_id': '_ecco/HistAndGeo/0739200300',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': 'This is a criminal biography/pamphlet recounting the life and trial of Richard Mosely, executed for murder. Criminal biographies of this period are conventionally classified as fiction in ESTC, as they typically blend factual reportage with sensationalized narrative embellishment.',
  'notes': 'This is a typical early 18th-century criminal biography pamphlet, detailing the life, trial, and execution of Richard Mosely for the murder of his grandmother Mary Payton in Sedgley, Staffordshire, in 1707. Such pamphlets were popular ephemeral literature, sold at executions and by chapbook sellers. While based on real events, they are conventionally grouped with fiction due to their heavy narrative embellishment and formulaic structure. The genre sits at the boundary between journalism, biography, and popular fiction.',
  'llm_confidence': 0.72,
  'genre_raw': 'Criminal biography'},
 {'_id': '_ecco/LitAndLang1/0250600500',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "Despite the subtitle 'A true story,' works with titles like 'The Lancashire Collier Girl' in this period are typically sentimental fiction or novellas presenting themselves as true accounts. The pattern of '[Place] [humble occupation] girl' is characteristic of late 18th-century sentimental fiction.",
  'notes': "The Lancashire Collier Girl: A True Story is a late 18th-century work that appears to be a short novel or tale in the sentimental tradition, likely published in the 1790s. The 'true story' subtitle was a common convention in fiction of this period to lend verisimilitude. The subject of a humble working-class girl suggests a sentimental or moral narrative about virtue in low life. The author is not identified on the title page.",
  'llm_confidence': 0.72,
  'genre_raw': 'Novel, sentimental'},
 {'_id': '_litlab/LL1560',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Poetry',
  'is_translated': False,
  'genre_source_reason': "Helen Maria Williams's 'Edwin and Eltruda' (1782) is a verse tale — a narrative poem in the legendary/sentimental mode, not prose fiction.",
  'notes': "Edwin and Eltruda: A Legendary Tale (1782) was Helen Maria Williams's first published work, issued anonymously as 'by a young lady.' It is a narrative poem in heroic couplets telling a tragic love story set in medieval England. Williams went on to become well known for her poetry and her letters from revolutionary France.",
  'llm_confidence': 0.9},
 {'_id': '_litlab/LL1221',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "The title explicitly identifies itself as 'a sentimental romance' and the structure ('in two volumes') is typical of late 18th-century prose fiction. This is a novel from the sentimental tradition.",
  'notes': 'The Birmingham Counterfeit; or, Invisible Spectator (c.1772) is an anonymous sentimental romance published in two volumes. The title suggests themes of deception and observation common in 18th-century fiction. It is a relatively obscure work of the period, not widely discussed in literary histories.',
  'llm_confidence': 0.85,
  'genre_raw': 'Novel, sentimental'},
 {'_id': '_ecco/LitAndLang1/0757400503',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': 'Desmond (1792) by Charlotte Smith is a well-known epistolary novel set against the backdrop of the French Revolution, combining a love story with political commentary.',
  'notes': 'Desmond (1792) by Charlotte Smith is an epistolary novel in which the titular character, Desmond, is in love with a married woman, Geraldine Verney, whose husband is dissolute and cruel. The novel is notable for its sympathetic treatment of the French Revolution and its progressive political views, which were controversial at the time. Smith was one of the most prominent novelists and poets of the late 18th century.',
  'llm_confidence': 0.95,
  'genre_raw': 'Novel, epistolary'},
 {'_id': '_tedjdh/K079595.001',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "The title explicitly states it is 'in imitation of Gil Blas,' the classic picaresque novel by Lesage, and follows the adventures of a character 'supposed to be written by himself,' a standard picaresque framing device.",
  'notes': "Modern Times; or, The Adventures of Gabriel Outcast (1785) by John Trusler is a picaresque novel modeled on Lesage's Gil Blas. Trusler (1735–1820) was an English clergyman, author, and eccentric publisher known for a wide range of works including conduct books, abridgments, and this satirical novel depicting contemporary English society through the adventures of its roguish protagonist.",
  'llm_confidence': 0.95,
  'genre_raw': 'Picaresque'},
 {'_id': '_tedjdh/K039355.000',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Poetry',
  'is_translated': False,
  'genre_source_reason': "Hannah Cowley's 'The Maid of Arragon' (1780) is a verse tale — a narrative poem rather than prose fiction. Despite the subtitle 'A Tale,' it is written in verse.",
  'notes': "The Maid of Arragon: A Tale (1780) by Hannah Cowley (née Parkhouse, 1743–1809) is a narrative poem. Cowley was primarily known as a dramatist (The Belle's Stratagem, 1780) but also wrote poetry. This work is in verse form and should be classified as poetry rather than fiction.",
  'llm_confidence': 0.82},
 {'_id': '_litlab/LL1372',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "The title 'The Matrons: Six Short Histories' suggests a collection of short prose fiction narratives. This appears to be a mid-18th-century collection of tales, possibly inspired by or related to the 'Matron of Ephesus' tradition from Petronius, presenting stories of women's conduct.",
  'notes': "The Matrons (1762) is a collection of six short tales, likely prose fiction narratives centered on female characters. The work may draw on the classical tradition of the Matron of Ephesus story from Petronius's Satyricon, a popular theme in 18th-century literature. The anonymous authorship and the use of 'histories' in the subtitle is typical of 18th-century fiction collections. The term 'histories' in this period frequently denotes fictional narratives rather than factual accounts.",
  'llm_confidence': 0.72,
  'genre_raw': 'Tale'},
 {'_id': '_ecco/LitAndLang1/0013500201',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "Joseph de Maimieux was a French author known for sentimental novels; 'Le comte de Saint-Méran' appears to be a French-language novel published in the late 18th century. Its appearance in an English catalog may indicate it was printed in London for a French-reading audience or is a cataloging artifact.",
  'notes': "Joseph de Maimieux (1753–1820) was a French writer and inventor of the 'pasigraphie' universal writing system. He also wrote novels and other literary works. 'Le comte de Saint-Méran' is a French-language novel, likely sentimental in character, consistent with the literary fashions of the 1780s. This text appears in English catalogs but is in French, not a translation into English.",
  'llm_confidence': 0.7,
  'genre_raw': 'Novel, sentimental'},
 {'_id': '_litlab/LL0718',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Biography',
  'is_translated': False,
  'genre_source_reason': 'Arthur Maynwaring (1668–1712) was a real person — a Whig political writer and Kit-Cat Club member. This is a posthumous collection of his works with a biographical account, not fiction.',
  'notes': "Arthur Maynwaring (1668–1712) was an English political writer, journalist, and Whig propagandist closely associated with the Duchess of Marlborough and the Kit-Cat Club. This posthumous volume, likely edited by John Oldmixon and published around 1715, combines a biographical life with a collection of Maynwaring's previously unpublished writings, including political tracts, translations, and verse. It is a biography and collected works, not fiction.",
  'llm_confidence': 0.92},
 {'_id': '_litlab/LL1495',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "'The history of Lady Frances Tylney' follows the typical naming convention of 18th-century sentimental novels, with fictional-sounding character names and the keyword 'True delicacy' suggesting a sentimental theme.",
  'notes': "This appears to be an anonymous sentimental novel from the latter half of the 18th century. The title structure — an abstract moral quality followed by 'the history of' fictional characters — is characteristic of the period's sentimental fiction. The names Lady Frances Tylney and Henry Cecil suggest aristocratic protagonists typical of the genre. Published circa 1769.",
  'llm_confidence': 0.85,
  'genre_raw': 'Novel, sentimental'},
 {'_id': '_hathi_englit/mdp/39015030208071',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "This title follows the convention of epistolary fiction popular in the late 18th century, presenting fictional letters from a noble figure as a framing device. The anonymous authorship and the generic 'peeress of England' suggest a fictional construct rather than genuine correspondence.",
  'notes': 'Letters from a Peeress of England to her Eldest Son (c. 1784) is an epistolary work that presents itself as advice from a noblewoman to her son. While it could be a genuine conduct book in letter form, the anonymous publication and the convention of the period strongly suggest it is either epistolary fiction or a didactic work using a fictional epistolary frame. It may border on conduct literature rather than pure fiction.',
  'llm_confidence': 0.72,
  'genre_raw': 'Novel, epistolary'},
 {'_id': '_ecco/HistAndGeo/0127400400',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "This is an 'it-narrative' or 'novel of circulation' told from the perspective of a cat, a popular subgenre in the mid-to-late 18th century.",
  'notes': 'The Life and Adventures of a Cat (1760) is an anonymous it-narrative, a genre in which animals or objects narrate their own life stories as they pass through various owners and situations. These works typically served as vehicles for social satire, offering commentary on human behavior through the eyes of a non-human narrator. This particular work follows a cat named Tom through various adventures and was popular enough to be reprinted multiple times.',
  'llm_confidence': 0.9,
  'genre_raw': 'Novel, It Narrative'},
 {'_id': '_hathi_englit/mdp/39015078561373',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "This is Charles Gildon's satirical attack on Daniel Defoe, published in 1719 shortly after Robinson Crusoe. It parodies Defoe's life and work using the format of Crusoe's title.",
  'notes': "The Life and Strange Surprizing Adventures of Mr. D---- De F-- (1719) by Charles Gildon is a satirical pamphlet attacking Daniel Defoe, parodying the title and style of Robinson Crusoe. Gildon mocks Defoe's career, politics, and literary pretensions. It includes a dialogue in which Crusoe and Friday confront their creator. While it has a satirical narrative frame, it is primarily a personal attack and literary satire rather than a sustained novel.",
  'llm_confidence': 0.95,
  'genre_raw': 'Fiction, satire'},
 {'_id': '_litlab/LL0085',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Letters',
  'is_translated': True,
  'genre_source_reason': "Bellegarde's letters are didactic/conduct letters addressed to a lady of the court on 'curious and useful subjects,' making them closer to epistolary essays or conduct literature than fiction. The title explicitly states they are translated from French.",
  'notes': 'Jean-Baptiste Morvan de Bellegarde (1648–1734) was a French abbé and prolific author of conduct books, moral reflections, and letters on polite behavior and learning. His works were widely translated into English in the early 18th century. These letters, addressed to a lady of the French court, are didactic in nature, offering advice and reflections on various subjects rather than constituting a fictional narrative. The English translation includes a preface by the translator.',
  'llm_confidence': 0.75,
  'translated_from': 'French'},
 {'_id': '_tedjdh/K000637.000',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "This is the third part of Arbuthnot's 'Law is a Bottomless Pit' (1712), the John Bull political satire series, which uses sustained fictional allegory with characters representing nations (John Bull = England, Nicholas Frog = the Dutch, etc.) to satirize the War of the Spanish Succession.",
  'notes': "John Bull Still in His Senses (1712) by John Arbuthnot is the third pamphlet in a series of five that collectively form 'The History of John Bull.' These satirical allegories, written to support the Tory push for peace during the War of the Spanish Succession, created the enduring character of John Bull as a personification of England. The series uses a fictional lawsuit narrative to allegorize European politics. Arbuthnot was a physician, mathematician, and member of the Scriblerus Club alongside Swift and Pope.",
  'llm_confidence': 0.92,
  'genre_raw': 'Fiction, satire'},
 {'_id': '_tedjdh/K102171.000',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Criticism',
  'is_translated': False,
  'genre_source_reason': "This appears to be a critical commentary on Sterne's Tristram Shandy, published under the pseudonym 'Jeremiah Kunastrokius M.D.' It is not the novel itself but rather explanatory remarks upon it. The attribution to Sterne in the catalog may reflect the subject matter rather than actual authorship; such parasitic commentaries were common.",
  'notes': "This is one of several contemporary responses to Laurence Sterne's The Life and Opinions of Tristram Shandy, Gentleman (1759–1767). 'Jeremiah Kunastrokius' is a comic pseudonym (the name appears as a character reference in Tristram Shandy itself). The work purports to explain the morals and politics of Sterne's novel. It is likely not by Sterne himself but is cataloged under his name because it concerns his work. It belongs to the genre of critical commentary or satirical explication rather than fiction proper.",
  'llm_confidence': 0.72},
 {'_id': '_ecco/LitAndLang1/0375900101',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': True,
  'genre_source_reason': 'This is a continuation of the Arabian Nights, translated from the French edition by Dom Chavis and Jacques Cazotte, consisting of oriental tales in the frame narrative tradition.',
  'notes': "Arabian Tales (1792) is an English translation of the 'Suite des Mille et une Nuits' compiled by Dom Denis Chavis, a Syrian priest, and Jacques Cazotte, the French author. Published in French as part of the Cabinet des fées (vols. 38-41, 1788-1790), it purported to be translated from an Arabic manuscript but was largely fabricated or heavily embellished by Cazotte. The English translation appeared in the 1790s and was marketed as a continuation of Galland's famous Arabian Nights Entertainments.",
  'llm_confidence': 0.95,
  'genre_raw': 'Tale, oriental',
  'translated_from': 'French'},
 {'_id': '_tedjdh/K109095.002',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Criticism',
  'is_translated': True,
  'genre_source_reason': "Charlotte Lennox's Shakespear Illustrated is a work of literary criticism that collects and translates the source narratives for Shakespeare's plays, accompanied by critical remarks comparing the sources to the plays. Despite containing translated fiction, the work itself is a critical study.",
  'notes': "Shakespear Illustrated (1753-54, 3 vols.) by Charlotte Lennox (author of The Female Quixote, 1752) was one of the first systematic studies of Shakespeare's sources. It translates the Italian novellas, chronicles, and romances that Shakespeare drew upon, with Lennox's critical commentary often arguing that Shakespeare degraded his sources, particularly in his treatment of female characters. Samuel Johnson contributed a dedication. The work contains translations from Italian and other languages but is fundamentally a work of literary criticism.",
  'llm_confidence': 0.95},
 {'_id': '_hathi_englit/nyp/33433074918768',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "George Walker's The Vagabond (1799) is a well-known anti-Jacobin novel satirizing the radical philosophies of Godwin, Holcroft, and others.",
  'notes': 'The Vagabond (1799) by George Walker is an anti-Jacobin novel that follows a character influenced by radical philosophy (particularly that of William Godwin) through a series of misadventures designed to demonstrate the absurdity and danger of revolutionary ideas. It is one of the most prominent examples of the conservative novelistic response to the French Revolution and radical thought in 1790s England.',
  'llm_confidence': 0.9,
  'genre_raw': 'Novel, anti-Jacobin'},
 {'_id': '_ecco_tcp/K030489.000',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Fiction',
  'is_translated': False,
  'genre_source_reason': "This is one of Hannah More's Cheap Repository Tracts, short moral tales written for popular distribution among the poor. Despite their brevity and didactic purpose, they are prose fiction.",
  'notes': "The Bad Bargain: or, The World Set Up to Sale is one of Hannah More's Cheap Repository Tracts (1795–1798), a series of moral and religious tales designed to counter radical and irreligious popular literature. These tracts were distributed widely and cheaply, functioning as improving chapbooks. More wrote many of them herself, using simple narratives and allegories to convey Christian moral lessons.",
  'llm_confidence': 0.85,
  'genre_raw': 'Chapbook'},
 {'_id': '_tedjdh/K102448.001',
  'genre_source': 'llm:claude-opus-4-6',
  'genre': 'Essay',
  'is_translated': False,
  'genre_source_reason': "The Babbler is a collection of periodical essays by Hugh Kelly, originally published in Owen's Weekly Chronicle. It is a compilation of moral and entertaining essays in the tradition of The Spectator, not fiction.",